#!/bin/sh

unset OS_LOGDIR FREEVO_LOGDIR OS_STATICDIR FREEVO_STATICDIR OS_CACHEDIR FREEVO_CACHEDIR FREEVO_SHARE FREEVO_CONTRIB FREEVO_SCRIPT FREEVO_CONFIG LD_PRELOAD SDL_VIDEODRIVER FREEVO_LOCALE FREEVO_PYTHON

test -r /etc/freevo/debconf.sh && . /etc/freevo/debconf.sh

test -r /etc/default/freevo && . /etc/default/freevo

[ -d $HOME/log  ] || mkdir $HOME/log
[ -f $HOME/log/Xfreevo.log  ] && mv $HOME/log/Xfreevo.log{,~}

exec >> $HOME/log/Xfreevo.log
exec 2>> $HOME/log/Xfreevo.log

# FIXME: implement better way
#
#  use xrandr on the running X to find the current resolution and put that in
#  the freevo.conf. The X server has chosen the best resolution anyways.
#
#  This script is basically the freevo+log script, which is started by tty9
#  (upstart /etc/event.d/tty9), which is in fact an openvt + su + startx.

cat /etc/freevo/freevo.conf |grep -v geometry > /tmp/a.conf
echo geometry = `xrandr |grep '*'|awk '{print $1}'` >> /tmp/a.conf
mkdir ~/.freevo
cp /tmp/a.conf ~/.freevo/freevo.conf || exit 1

# start freevo
exec /usr/bin/freevo.real "$@"
