#!/bin/bash

(

. /etc/default/rcS
[ -f /forcefsck ] && force_fsck="--force-fsck"
[ "$FSCKFIX" = "yes" ] && fsck_fix="--fsck-fix"

# set $LANG so that messages appearing in plymouth are translated
if [ -r /etc/default/locale ]; then
. /etc/default/locale
export LANG LANGUAGE LC_MESSAGES
elif [ -r /etc/environment ]; then
. /etc/environment
export LANG LANGUAGE LC_MESSAGES
fi

echo "mounting"

mount -o rw,remount /

[ -d /dev  ] || mkdir -m 0755 /dev
mount -t tmpfs -o mode=0755 none /dev
mknod -m 0600 /dev/console c 5 1
mknod /dev/null c 1 3

[ -d /dev/pts ]  || mkdir /dev/pts
mount -t devpts -o noexec,nosuid,gid=5,mode=0620 none /dev/pts || echo "OK"

# from here on, panic is possible, as /dev/console exists

# mount /sys and /proc
[ -d /sys  ]     || mkdir /sys
[ -d /proc ]     || mkdir /proc
[ -d /var/lock ] || mkdir -p /var/lock
[ -d /var/run ]  || mkdir -p /var/run
[ -d /tmp  ]     || mkdir /tmp
mount -t sysfs -o nodev,noexec,nosuid none /sys || echo "OK"
mount -t proc  -o nodev,noexec,nosuid none /proc || echo "OK"
umount /var/run || echo "OK unmount /var/run"
umount /var/lock || echo "OK unmount /var/lock"
umount /tmp || echo "OK unmount /tmp"
mount -t tmpfs  -o rw,nosuid,mode=0755 none /var/run || echo "OK"
mount -t tmpfs  -o rw,noexec,nosuid,nodev none /var/lock || echo "OK"
mount -t tmpfs /dev/shm /tmp || echo "OK"

echo "Starting udev"
udevd --daemon --resolve-names=never

grep '^[^#]' /etc/modules |
	while read module args
	do
	    [ "$module" ] || continue
	    modprobe $module $args || :
	done

# swap
modprobe ps3vram

echo "Making swap"
mkswap /dev/ps3vram

echo "Mounting others"
mount -a


# Networking
echo "Mounting others"
mount -a

echo "Starting udevadm trigger"
udevadm trigger

#( udevadm trigger --subsystem-match=block; \
  #udevadm trigger --subsystem-nomatch=block; ) &

echo "Starting udevadm settle"
udevadm settle --timeout=0 --quiet


mkdir -p /var/run/network
ifup -a


echo "Done mounting"
)&
